const express = require('express');
const mongoose = require('mongoose');
const nvidiaClient = require('./services/nvidiaClient');
const cors = require('cors');
const rateLimit = require('express-rate-limit');
const http = require('http');
const { Server } = require('socket.io');
require('dotenv').config();

const Expense = require('./models/Expense');
const Policy = require('./models/Policy');

const app = express();
const server = http.createServer(app);
const io = new Server(server, {
  cors: { origin: '*' }
});

const PORT = process.env.PORT || 3978;

// ==================== MIDDLEWARE ====================

app.use(cors());
app.use(express.json());

const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, 
  max: 100, 
  message: { type: 'message', text: 'Too many requests, please try again in 15 minutes.' }
});

const aiLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, 
  max: 30, 
  message: { type: 'message', text: 'AI quota exceeded for this hour. Please contact admin.' }
});

app.use('/api/', apiLimiter);
app.use('/api/messages', aiLimiter);

const authenticateAdmin = (req, res, next) => {
  const apiKey = req.headers['x-api-key'];
  if (apiKey === process.env.ADMIN_API_KEY) return next();
  return res.status(401).json({ error: 'Unauthorized: Valid Admin API Key required' });
};

// ==================== DATABASE ====================

mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('✅ Connected to MongoDB'))
  .catch(err => console.error('❌ MongoDB connection error:', err));

async function seedDatabase() {
  const policyCount = await Policy.countDocuments();
  if (policyCount === 0) {
    console.log('🌱 Seeding initial policies...');
    await Policy.insertMany([
      { ruleName: 'Max Item Limit', threshold: 5000, category: 'general', description: 'Expenses exceeding $5,000 are strictly prohibited without board approval.', severity: 'HIGH' },
      { ruleName: 'Pre-Approval Threshold', threshold: 2000, category: 'travel', description: 'Travel expenses > $2,000 require pre-approval from the department head.', severity: 'MEDIUM' },
      { ruleName: 'Vendor Approval', category: 'vendors', description: 'All vendors must be on the approved corporate list.', severity: 'MEDIUM' },
      { ruleName: 'Receipt Requirement', threshold: 25, category: 'documentation', description: 'Digital receipts are required for all expenses over $25.', severity: 'LOW' }
    ]);
  }
  const expenseCount = await Expense.countDocuments();
  if (expenseCount === 0) {
    console.log('🌱 Seeding initial expenses...');
    await Expense.insertMany([
      { submitter: 'john.doe@company.com', amount: 1500, vendor: 'Acme Corp', category: 'travel', approved: false },
      { submitter: 'jane.smith@company.com', amount: 2500, vendor: 'Unapproved Vendor', category: 'conference', approved: false },
      { submitter: 'bob.johnson@company.com', amount: 150, vendor: 'Office Supplies Ltd', category: 'supplies', approved: true },
      { submitter: 'alice.williams@company.com', amount: 8000, vendor: 'TechVendor Inc', category: 'software', approved: false }
    ]);
  }
}
seedDatabase();

function createAdaptiveCard(title, facts, status = 'Attention') {
  return {
    type: 'message',
    attachments: [{
      contentType: 'application/vnd.microsoft.card.adaptive',
      content: {
        type: 'AdaptiveCard',
        version: '1.4',
        body: [
          { type: 'TextBlock', text: title, weight: 'Bolder', size: 'Medium', color: status === 'Success' ? 'Good' : 'Attention' },
          { type: 'FactSet', facts: facts.map(f => ({ title: f.label, value: f.value })) },
          { type: 'TextBlock', text: 'Generated by Finance Intelligence Agent', size: 'Small', isSubtle: true, spacing: 'Medium' }
        ],
        actions: [{ type: 'Action.OpenUrl', title: 'View Company Policy', url: 'https://company.sharepoint.com/policies' }]
      }
    }]
  };
}

// ==================== AGENT ENDPOINTS ====================

app.get('/', (req, res) => {
  res.type('html').send(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Finance Intelligence Agent</title>
  <style>
    :root {
      color-scheme: light dark;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #f6f7f9;
      color: #17202a;
    }
    body {
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      background:
        linear-gradient(135deg, rgba(8, 84, 110, 0.10), transparent 38%),
        linear-gradient(315deg, rgba(20, 121, 82, 0.12), transparent 40%),
        #f6f7f9;
    }
    main {
      width: min(880px, calc(100vw - 32px));
      display: grid;
      gap: 18px;
    }
    section {
      background: rgba(255, 255, 255, 0.92);
      border: 1px solid #d8dee8;
      border-radius: 8px;
      box-shadow: 0 20px 60px rgba(30, 41, 59, 0.12);
      padding: 24px;
    }
    h1 {
      margin: 0 0 8px;
      font-size: clamp(28px, 4vw, 44px);
      line-height: 1.05;
      letter-spacing: 0;
    }
    p {
      margin: 0;
      color: #4b5563;
      line-height: 1.6;
    }
    form {
      display: flex;
      gap: 10px;
      margin-top: 18px;
    }
    input {
      flex: 1;
      min-width: 0;
      border: 1px solid #cbd5e1;
      border-radius: 6px;
      padding: 12px 14px;
      font: inherit;
      background: white;
      color: #111827;
    }
    button {
      border: 0;
      border-radius: 6px;
      padding: 12px 16px;
      font: inherit;
      font-weight: 700;
      background: #0f766e;
      color: white;
      cursor: pointer;
    }
    button:disabled {
      cursor: wait;
      opacity: 0.65;
    }
    pre {
      min-height: 180px;
      max-height: 420px;
      overflow: auto;
      white-space: pre-wrap;
      word-break: break-word;
      background: #101828;
      color: #e5e7eb;
      border-radius: 8px;
      padding: 16px;
      margin: 0;
      font-size: 14px;
      line-height: 1.5;
    }
    .chips {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      margin-top: 14px;
    }
    .chips button {
      background: #e7f5f2;
      color: #115e59;
      border: 1px solid #b6e1d9;
      font-weight: 650;
      padding: 8px 10px;
    }
    @media (max-width: 640px) {
      body {
        place-items: start center;
        padding: 16px 0;
      }
      section {
        padding: 18px;
      }
      form {
        flex-direction: column;
      }
      button {
        width: 100%;
      }
    }
  </style>
</head>
<body>
  <main>
    <section>
      <h1>Finance Intelligence Agent</h1>
      <p>Send a finance or compliance command to the local agent API.</p>
      <form id="message-form">
        <input id="message-input" value="review expense reports" autocomplete="off" aria-label="Agent command">
        <button id="send-button" type="submit">Send</button>
      </form>
      <div class="chips" aria-label="Example commands">
        <button type="button" data-command="review expense reports">Review expenses</button>
        <button type="button" data-command="check policy compliance">Compliance</button>
        <button type="button" data-command="identify spending anomalies">Anomalies</button>
        <button type="button" data-command="optimize budget">Optimize</button>
        <button type="button" data-command="generate compliance report">Report</button>
      </div>
    </section>
    <pre id="response-output">Ready.</pre>
  </main>
  <script>
    const form = document.querySelector('#message-form');
    const input = document.querySelector('#message-input');
    const output = document.querySelector('#response-output');
    const sendButton = document.querySelector('#send-button');

    async function sendMessage(text) {
      sendButton.disabled = true;
      output.textContent = 'Working...';
      try {
        const response = await fetch('/api/messages', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ text })
        });
        const data = await response.json();
        output.textContent = JSON.stringify(data, null, 2);
      } catch (error) {
        output.textContent = error.message;
      } finally {
        sendButton.disabled = false;
      }
    }

    form.addEventListener('submit', (event) => {
      event.preventDefault();
      sendMessage(input.value.trim());
    });

    document.querySelectorAll('[data-command]').forEach((button) => {
      button.addEventListener('click', () => {
        input.value = button.dataset.command;
        sendMessage(button.dataset.command);
      });
    });
  </script>
</body>
</html>`);
});

app.get('/health', (req, res) => {
  res.json({ status: 'Finance & Compliance Agent is running (Enterprise Grade)' });
});

app.post('/api/messages', async (req, res) => {
  const { text } = req.body;
  if (!text || typeof text !== 'string') {
    return res.status(400).json({ type: 'message', text: 'Invalid input. Please provide a text command.' });
  }
  try {
    if (text.toLowerCase().includes('review expense') || text.toLowerCase().includes('expense reports')) {
      res.json(await handleReviewExpenses());
    } else if (text.toLowerCase().includes('compliance') || text.toLowerCase().includes('policy')) {
      res.json(await handleComplianceCheck());
    } else if (text.toLowerCase().includes('anomal') || text.toLowerCase().includes('unusual')) {
      res.json(await handleAnomalyDetection());
    } else if (text.toLowerCase().includes('optimize') || text.toLowerCase().includes('budget')) {
      res.json(await handleBudgetOptimization());
    } else if (text.toLowerCase().includes('report')) {
      res.json(await handleGenerateReport());
    } else {
      res.json({
        type: 'message',
        text: 'I can help you with:\n• Review expense reports\n• Check policy compliance\n• Identify spending anomalies\n• Optimize budget (NVIDIA cuOpt)\n• Generate compliance reports'
      });
    }
  } catch (error) {
    console.error('[ERROR]', error);
    res.status(500).json({ type: 'message', text: 'An internal error occurred.' });
  }
});

app.post('/api/expenses', authenticateAdmin, async (req, res) => {
  try {
    const { submitter, amount, vendor, category, approved } = req.body;
    if (!submitter || !amount || !vendor) {
      return res.status(400).json({ error: 'Missing required fields' });
    }
    const expense = await Expense.create({ submitter, amount, vendor, category, approved });
    checkAndEmitViolation(expense);
    res.status(201).json(expense);
  } catch (e) { res.status(400).json({ error: 'Invalid data provided' }); }
});

app.get('/api/expenses', authenticateAdmin, async (req, res) => {
  try {
    const expenses = await Expense.find().lean();
    res.json(expenses);
  } catch (e) { res.status(500).json({ error: 'Error fetching expenses' }); }
});

app.get('/api/policies', authenticateAdmin, async (req, res) => {
  try {
    const policies = await Policy.find().lean();
    res.json(policies);
  } catch (e) { res.status(500).json({ error: 'Error fetching policies' }); }
});

app.get('/api/analytics', authenticateAdmin, async (req, res) => {
  try {
    const total = await Expense.aggregate([
      { $group: { _id: null, totalAmount: { $sum: '$amount' }, count: { $sum: 1 } } }
    ]);
    res.json(total[0] || { totalAmount: 0, count: 0 });
  } catch (e) { res.status(500).json({ error: 'Error calculating analytics' }); }
});

async function handleReviewExpenses() {
  const expenses = await Expense.find().lean();
  const policies = await Policy.find().lean();
  const violations = [];
  const reviewPromises = expenses.map(async (expense) => {
    const limitPolicy = policies.find(p => p.ruleName === 'Max Item Limit');
    if (limitPolicy && expense.amount > limitPolicy.threshold) {
      const citation = await nvidiaClient.queryRAG('amount limit', policies);
      return { id: expense._id, issue: `Amount $${expense.amount} exceeds limit $${limitPolicy.threshold}`, citation, severity: limitPolicy.severity };
    }
    const preAppPolicy = policies.find(p => p.ruleName === 'Pre-Approval Threshold');
    if (preAppPolicy && expense.amount > preAppPolicy.threshold && !expense.approved) {
      const citation = await nvidiaClient.queryRAG('pre-approval', policies);
      return { id: expense._id, issue: `Pre-approval required for $${expense.amount}`, citation, severity: preAppPolicy.severity };
    }
    return null;
  });
  const results = await Promise.all(reviewPromises);
  const filteredViolations = results.filter(v => v !== null);
  const facts = [
    { label: 'Total Reviewed', value: expenses.length.toString() },
    { label: 'Violations', value: filteredViolations.length.toString() },
    ...filteredViolations.map(v => ({ label: `Expense ${v.id.toString().slice(-4)}`, value: `${v.issue} | ${v.citation}` }))
  ];
  return createAdaptiveCard('Expense Review Summary', facts, filteredViolations.length > 0 ? 'Attention' : 'Success');
}

async function handleComplianceCheck() {
  const expenses = await Expense.find().lean();
  const policies = await Policy.find().lean();
  const limitPolicy = policies.find(p => p.ruleName === 'Max Item Limit');
  const compliantCount = expenses.filter(e => limitPolicy ? e.amount <= limitPolicy.threshold : true).length;
  const facts = [
    { label: 'Total Expenses', value: expenses.length.toString() },
    { label: 'Compliant', value: compliantCount.toString() },
    { label: 'Compliance Rate', value: `${((compliantCount / expenses.length) * 100).toFixed(1)}%` },
  ];
  return createAdaptiveCard('Compliance Status Report', facts, compliantCount === expenses.length ? 'Success' : 'Attention');
}

async function handleAnomalyDetection() {
  const expenses = await Expense.find().lean();
  const avg = expenses.reduce((sum, e) => sum + e.amount, 0) / expenses.length;
  const anomalies = expenses.filter(e => e.amount > avg * 1.5);
  const facts = [
    { label: 'Avg Expense', value: `$${avg.toFixed(2)}` },
    { label: 'Anomalies Found', value: anomalies.length.toString() },
    ...anomalies.map(a => ({ label: `Expense ${a._id.toString().slice(-4)}`, value: `$${a.amount} (High)` }))
  ];
  return createAdaptiveCard('Anomaly Detection Report', facts, anomalies.length > 0 ? 'Attention' : 'Success');
}

async function handleBudgetOptimization() {
  const expenses = await Expense.find().lean();
  const suggestion = await nvidiaClient.optimizeBudget(expenses);
  return createAdaptiveCard('Budget Optimization (NVIDIA cuOpt)', [
    { label: 'Current Status', value: 'Analyzed' },
    { label: 'Recommendation', value: suggestion }
  ], 'Success');
}

async function handleGenerateReport() {
  const expenses = await Expense.find().lean();
  const total = expenses.reduce((sum, e) => sum + e.amount, 0);
  const facts = [
    { label: 'Total Processed', value: expenses.length.toString() },
    { label: 'Total Spend', value: `$${total.toFixed(2)}` },
    { label: 'Status', value: 'Audit-Ready' }
  ];
  return createAdaptiveCard('Compliance Audit Report', facts, 'Success');
}

async function checkAndEmitViolation(expense) {
  const policies = await Policy.find().lean();
  const limitPolicy = policies.find(p => p.ruleName === 'Max Item Limit');
  if (limitPolicy && expense.amount > limitPolicy.threshold) {
    const citation = await nvidiaClient.queryRAG('amount limit', policies);
    io.emit('compliance-alert', {
      type: 'VIOLATION',
      severity: limitPolicy.severity,
      message: `High-risk expense detected: $${expense.amount} by ${expense.submitter}`,
      citation: citation
    });
  }
}

server.listen(PORT, () => {
  console.log(`\n🚀 Finance Intelligence Agent (Production Grade) running on http://localhost:${PORT}`);
  console.log('📚 Endpoints:');
  console.log(`   - GET  /health`);
  console.log(`   - POST /api/messages`);
  console.log(`   - POST /api/expenses (Admin Only)`);
  console.log(`   - GET /api/analytics (Admin Only)`);
  console.log(`   - GET /api/expenses (Admin Only)`);
  console.log(`   - GET /api/policies (Admin Only)`);
  console.log(`   - WebSocket: ws://localhost:${PORT}`);
});

module.exports = app;
